server:
  port: 8082
  servlet:
      contextPath: /plouf
spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/plouf?user=root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.dozer: ERROR
    org.springframework: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
debug: true